import fs from 'fs';

import queryOverpass from '@derhuerst/query-overpass';

function generate_overpass_query(wikidata_pairs) {
	const types = Array.from(wikidata_pairs.keys());
	console.log(types);
	const query = '[out:json][timeout:25];'
    + 'area(id:3600186382)->.searchArea;'
	+ '('
	+ types.map(type => 
		`nwr["${type}:wikidata"~"^${Array.from(wikidata_pairs.get(type)).join('|')}$"](area.searchArea);`
	).join('')
	+ ');'
	+ 'out center;';
	return query;
}

export async function fetch_all_osm_data(spiders, retry=false) {
	const wikidata_pairs = spiders.reduce((acc, spider) => {
		spider.osm.forEach(osm_item => {
			const [type, wikidata] = osm_item.wikidata;
			if(!acc.has(type)) {
				acc.set(type, new Set());
			}
			acc.get(type).add(wikidata);
		});
		return acc;
	}, new Map());
	const query = generate_overpass_query(wikidata_pairs);
	console.log('Querying Overpass Turbo');
	
	console.log(query);
	let to_return;
	if(fs.existsSync('cache') && fs.existsSync('cache/osm_data.geojson')) {
		console.log('Using cached OSM data');
		to_return = JSON.parse(fs.readFileSync('cache/osm_data.geojson'));
	}
	else {
		to_return = await queryOverpass(query, true);
		if(!fs.existsSync('cache')) {
			fs.mkdirSync('cache');
		}
		fs.writeFileSync('cache/osm_data.geojson', JSON.stringify(to_return));
	}
	if(to_return.length==0){
		if(retry) {
			console.error('empty result again, terminating');
			process.exit(1);
		}

		console.error('ovepass returned empty result set, retrying');

		to_return = await fetch_all_osm_data(overpass_pairs, true);
	}
	preprocess_osm_data(to_return);
	return to_return;
}

function preprocess_osm_data(data) {
    data.forEach((item, index) => {
		if(item.nodes) {
			delete data[index].nodes;
        }
        if(item.center) {
			data[index].coordinates = [item.center.lat, item.center.lon];
            delete data[index].center;
        }
        else {
			data[index].coordinates = [item.lat, item.lon];
            delete data[index].lat;
            delete data[index].lon;
        }
		
		if(item.tags.atm === 'yes' && item.tags.amenity === 'bank'){
			let duplicate = JSON.parse(JSON.stringify(item));
			duplicate.tags = {
				amenity: 'atm',
				wikidata: item.wikidata,
				'generator:autogenerated': 'yes',
				'generator:original_item': `${item.type}/${item.id}`,
				'generator:based_on': 'atm=yes'

			};
			data.push(duplicate);
		}
    });
}